### ISSUE TITLE
Web Scraping

### ISSUE THREAD

**Issue by John4064** [John4064/CSGO-API#22]
Finish the development of the web scraping component of this API to gather all match data of hltv.org.

**Comment by dpielemeier** [comment]
👍
Hopefully I'll be able to learn these tools some day & do some real analysis

**Comment by dpielemeier** [comment]
> Finish the development of the web scraping component of this API to gather all match data of hltv.org.

👍
Hopefully I'll be able to learn these tools someday and perform some real data analysis
