### ISSUE TITLE
Todo: Add a check to verify if we need to make more api calls or the amount of matches = db entries

### ISSUE THREAD

**Issue by John4064** [John4064/CSGO-API#69]
Todo located in MatchCollectionServiceImpl around like 120ish.

**Comment by divygobi** [comment]
I was looking to make my first contribution and almost made a PR here, but, if I'm understanding you correctly, I think this check would be buggy. If the amount of new scraped matches exceeds the initial amount of db match entries(idList.size()), the loop would terminate early and the rest of the new matches would not be added.

**Comment by John4064** [comment]
It would function as: After it grabs the amount of matches on hltv.org/results it would then make a db call where it grabs the count of db rows and if it doesnt match then we continue if it matches then we stop.

**Comment by John4064** [comment]
close #71
